# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
# collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: false
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     /:title.html
paginate: 10
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

include: ['_pages']

prose:
  rooturl: '_posts'
  siteurl: "http://danipindado.github.io/"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "inner"
      - name: "title"
        field:
          element: "text"
          label: "Title of the post"
          value: "My title"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "category"
        field:
          label: "category, e.g. article"
          element: "text"
          value: "article"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
